# Generated by Django 3.2.7 on 2021-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamientoCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(default=0)),
                ('nombreApellido', models.CharField(max_length=200)),
                ('interes', models.CharField(max_length=200)),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlujoChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.TimeField(auto_now_add=True)),
                ('chatNum', models.IntegerField(default=0)),
                ('origen', models.CharField(max_length=200)),
                ('interes', models.CharField(max_length=200)),
                ('agenda', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numOrden', models.IntegerField(default=0)),
                ('fechaEntrega', models.DateField()),
                ('nombreCliente', models.CharField(max_length=200)),
                ('certificadoGIA', models.CharField(blank=True, max_length=200, null=True)),
                ('primerAbono', models.IntegerField(default=0)),
                ('destinoPrimerAbono', models.CharField(max_length=200)),
                ('segundoAbono', models.IntegerField(default=0)),
                ('destinoSegundoAbono', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
