# Generated by Django 3.2.7 on 2021-10-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitasVentas', '0003_auto_20211001_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='tipoPiedraCentral',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipoPiedrasLaterales',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
