# Generated by Django 3.2.7 on 2021-10-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CitasVentas', '0004_auto_20211001_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='piedraCentral',
            new_name='caratCentral',
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='piedrasLaterales',
            new_name='caratLaterales',
        ),
    ]
